# Generated by Django 5.2.1 on 2025-05-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('dob', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('Bat', 'Batsmen'), ('Bowl', 'Bowler'), ('Wk-Bat', 'Wicket Keeper and Batsmen'), ('All', 'All rounder')], max_length=20)),
                ('num_test_matches', models.IntegerField()),
                ('num_odi_matches', models.IntegerField()),
                ('num_t20_matches', models.IntegerField()),
                ('totalruns_test_matches', models.IntegerField()),
                ('totalruns_odi_matches', models.IntegerField()),
                ('totalruns_t20_matches', models.IntegerField()),
            ],
        ),
    ]
